models/database.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

models/models.py
# noinspection PyUnresolvedReferences
from models.tables.event import Event
# noinspection PyUnresolvedReferences
from models.tables.login import Login
# noinspection PyUnresolvedReferences
from models.tables.match import Match
# noinspection PyUnresolvedReferences
from models.tables.permission import Permission
# noinspection PyUnresolvedReferences
from models.tables.player import Player
# noinspection PyUnresolvedReferences
from models.tables.result import Result
# noinspection PyUnresolvedReferences
from models.tables.tournament import Tournament
# noinspection PyUnresolvedReferences
from models.tables.user_permission import UserPermission
# noinspection PyUnresolvedReferences
from models.tables.users import Users
# noinspection PyUnresolvedReferences
from models.tables.players_event_seed import PlayersEventSeed

app.py
from flask import *
from flask_migrate import Migrate

from models.database import db
from modules.web.routes import web_app
from modules.user.routes import user_app
from modules.admin.routes import admin_app
from modules.player.routes import player_app

''' App Config '''
app = Flask(__name__)
app.secret_key = 'csc536'

'''Database setup'''

app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:uabadmintontournamentadmin@uabadmintontournament' \
                                        '.cw5ilorod8lo.us-east-2.rds.amazonaws.com:5432/uabadmintontournamentdb'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
'''Route management'''


app.register_blueprint(web_app)
app.register_blueprint(user_app)
app.register_blueprint(admin_app)
app.register_blueprint(player_app)

db.init_app(app)
with app.app_context():
    db.create_all()
migrate = Migrate(app, db)

modules/admin/routes.py
from flask import Blueprint, render_template, request, redirect

from modules.admin.dashboard_home import get_player_roaster
from modules.admin.dashboard_tournament import get_tournament_details,post_tournament_details
from modules.admin.dashboard_events import get_event_details, assign_seeding
from modules.admin.dashboard_matches import get_matches_details,set_matches_court_no_and_status, set_matches_result
from modules.admin.draws import make_draws
from modules.decoraters import admin_login_required

admin_app = Blueprint("admin", __name__)


@admin_app.route('/admin', methods=['GET', 'POST'])
@admin_login_required
def admin_dashboard():
    player_details = get_player_roaster()
    return render_template('admin/admin_dashboard.html', msg=player_details)


@admin_app.route('/admin/tournament', methods=['GET'])
@admin_login_required
def admin_form():
    tournament_details = get_tournament_details(request)
    return render_template('admin/admin_form.html', msg=tournament_details)


@admin_app.route('/admin/tournament_creation', methods=['POST'])
@admin_login_required
def admin_tournament_creation():
    if request.method == "POST":
        tournament_details = post_tournament_details(request)
        return render_template('admin/admin_form.html', msg=tournament_details)


@admin_app.route('/admin/events', methods=['GET'])
@admin_login_required
def admin_events():
    event_details = get_event_details()
    return render_template('admin/admin_events.html', msg=event_details)


@admin_app.route('/admin/enter_seed', methods=['POST'])
@admin_login_required
def enter_seed():
    if request.method == "POST":
        event_details = get_event_details()
        seed_updated_details = assign_seeding(request, event_details)
        return render_template('admin/admin_events.html', msg=seed_updated_details)


@admin_app.route('/admin/make_draw', methods=['GET', 'POST'])
@admin_login_required
def make_draw():
    make_draws()
    return redirect('/draws')
    
 
@admin_app.route('/admin/matches', methods=['GET', 'POST'])
@admin_login_required
def admin_matches():
    match_details = get_matches_details()
    return render_template('admin/admin_matches.html', msg=match_details)


@admin_app.route('/admin/update_matches', methods=['POST'])
@admin_login_required
def update_matches():
    if request.method == "POST":
        set_matches_court_no_and_status(request)
        get_updated_match_details = get_matches_details()
        return render_template('admin/admin_matches.html', msg=get_updated_match_details)


@admin_app.route('/admin/update_results', methods=['POST'])
@admin_login_required
def update_results():
    if request.method == "POST":
        print(request.form)
        set_matches_result(request)
        get_updated_match_details = get_matches_details()
        return render_template('admin/admin_matches.html', msg=get_updated_match_details)

modules/player/routes.py
from flask import Blueprint, request, render_template, session, redirect

from modules.decoraters import user_login_required
from modules.player.dashboard_home import edit_player_details, get_player_details

player_app = Blueprint("player", __name__)


@player_app.route('/dashboard', methods=['GET'])
@user_login_required
def player_dashboard():
    player_details = get_player_details(session['user_id'])
    return render_template('player/player_dashboard.html', msg=player_details)


@player_app.route('/edit_details', methods=['POST'])
@user_login_required
def update_player():
    if request.method == "POST":
        update_status, msg = edit_player_details(request, session['user_id'])  # vars for later data validation
        return redirect('/dashboard')

modules/user/routes.py
from flask import Blueprint, request, render_template, redirect, url_for
from modules.user.login import *
from modules.user.signup import user_signup

user_app = Blueprint("user", __name__)


@user_app.route('/signup', methods=['GET', 'POST'])
def signup():
    msg = user_signup(request)
    if msg == 'You have successfully registered !':
        return render_template('user/login.html', msg=msg)
    else:
        return render_template('user/signup.html', msg=msg)


@user_app.route('/signin', methods=['GET', 'POST'])
def signin():
    success_status, msg = user_signin(request)
    if success_status:
        if session['user_id'] == 1:
            return redirect(url_for('admin.admin_dashboard'))
        else:
            return redirect(url_for('player.player_dashboard'))
    else:
        return render_template('user/login.html', msg=msg)


@user_app.route('/logout', methods=['GET', 'POST'])
def logout():
    session['user_id'] = 0
    session['logged_in'] = False
    return redirect('/signin')

modules/web/routes.py
from flask import Blueprint, render_template, request

from modules.admin.dashboard_home import get_player_roaster
from modules.admin.dashboard_events import get_event_details
from modules.admin.dashboard_matches import get_public_matches_details
from modules.web.draw import return_events_with_draws
from modules.admin.dashboard_tournament import get_tournament_details

web_app = Blueprint("web", __name__)


@web_app.route('/', methods=['GET', 'POST'])
def home():
    tournament_overview = get_tournament_details(request)
    return render_template('web/home.html', msg = tournament_overview)


@web_app.route('/tournament')
def tournament():
    tournament_details = get_tournament_details(request)
    return render_template('web/tournament.html', msg = tournament_details)


@web_app.route('/players')
def public_view_players():
    player_details = get_player_roaster()
    return render_template('web/players.html', msg=player_details)


@web_app.route('/events')
def events():
    event_details = get_event_details()
    return render_template('web/events.html', msg=event_details)


@web_app.route('/draws')
def draws():
    draws_boolean, draws_info = return_events_with_draws()
    if draws_boolean:
        return render_template('web/draws.html', msg=draws_info)
    else:
        return render_template('web/draws.html')


@web_app.route('/matches')
def matches():
    match_details = get_public_matches_details()
    return render_template('web/matches.html', msg=match_details)

templates/user/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Login </title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body></br></br></br></br></br>
        <div align="center">
            <div align="center" class="border2">
                <div class="header1">
                    <h1><a class="word" href="{{url_for('web.home')}}">UA Badminton Club Tournament System</a></h1>
                </div></br></br></br>
                <div class="header">
                    <h1 class="word">User Login</h1>
                </div></br></br></br>
                <h2 class="word">
                    <form action="{{ url_for('user.signin') }}" method="post">
                        <div class="msg">{{ msg }}</div></br>
                        <label>Username:</label></br>
                        <input id="username" name="username" type="text" placeholder="Enter Your Username" class="textbox"/></br></br>
                        <label>Password:</label></br>
                        <input id="password" name="password" type="password" placeholder="Enter Your Password" class="textbox"/></br></br></br>
                        <input type="submit" class="btn" value="Sign In"></br></br>
                    </form>
                </h2>
                <p class="bottom">Don't have an account?  <a class="bottom" href="{{url_for('user.signup')}}"> Sign Up here</a></p>
            </div>
        </div>
    </body>
</html>

templates/user/signup.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Signup </title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body></br></br></br></br></br>
        <div align="center">
            <div align="center" class="border">
                <div class="header1">
                    <h1 class="word">UA Badminton Club Tournament System</h1>
                </div></br></br></br>
                <div class="header">
                    <h1 class="word">Player Sign-up</h1>
                </div></br></br></br>
                <h2 class="word">
                    <form action="{{ url_for('user.signup') }}" method="post">
                        <div class="msg">{{ msg }}</div>
                        <label>Username:</label></br>
                        <input id="username" name="username" type="text" placeholder="Enter Your Username" class="textbox"/></br></br>
                        <label>Password:</label></br>
                        <input id="password" name="password" type="password" placeholder="Enter Your Password" class="textbox"/></br></br>
                        <label>Confirm Password:</label></br>
                        <input id="password2" name="password2" type="password" placeholder="Enter Your Password again" class="textbox"/></br></br>
                        <label>First Name:</label></br>
                        <input id="firstname" name="firstname" type="text" placeholder="Enter Your First Name" class="textbox"/></br></br>
                        <label>Last Name:</label></br>
                        <input id="lastname" name="lastname" type="text" placeholder="Enter Your Last Name" class="textbox"/></br></br>
                        <label>Gender:</label></br>
                            <label>
                                <input type="radio" name="gender_optionsRadios" id="optionsRadios1" value="m">Male
                            </label>
                            <label>
                                <input type="radio" name="gender_optionsRadios" id="optionsRadios2" value="f">Female
                            </label>
                            <label>
                                <input type="radio" name="gender_optionsRadios" id="optionsRadios3" value="o">Others
                            </label></br></br>
                        <label>Email:</label></br>
                        <input id="email" name="email" type="email" placeholder="Enter Your Email Address" class="textbox"/></br></br>
                        <input type="submit" class="btn" value="Sign Up"></br>
                    </form>
                </h2>
                <p class="bottom">Already have an account?  <a class="bottom" href="{{url_for('user.signin')}}"> Sign In here</a></p>
            </div>
        </div>
    </body>
</html>

templates/web/draws.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>UA Badminton Tournament</title>
	<!-- Bootstrap Styles-->
    <link href="static/bootstrap.css" rel="stylesheet" />
     <!-- FontAwesome Styles-->
    <link href="static/font-awesome.css" rel="stylesheet" />
     <!-- Morris Chart Styles-->

        <!-- Custom Styles-->
    <link href="static/adminCustomStyle.css" rel="stylesheet" />
    <link href="static/drawStyle.css" rel="stylesheet" />
     <!-- Google Fonts-->
   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
     <!-- TABLE STYLES-->
    <link href="static/dataTables.bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div id="wrapper-public">
        <nav class="navbar navbar-default top-navbar-public" role="navigation">
            <div class="navbar-header-public">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url_for('web.home')}}">UA Badminton Tournament</a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="{{url_for('user.signin')}}" >Log In</a>
                </li>
            </ul>
        </nav>
        <!--/. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.home')}}"><i class="fa fa-dashboard"></i> HOME</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.tournament')}}"><i class="fa fa-edit"></i> Tournament</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.public_view_players')}}"><i class="fa fa-desktop"></i> Players</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.events')}}"><i class="fa fa-desktop"></i> Events</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.draws')}}"><i class="fa fa-desktop"></i> Draws</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.matches')}}"><i class="fa fa-table"></i> Matches</a>
                    </li>
                </ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
			    <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            Draws <small></small>
                        </h1>
                    </div>
                </div>
                {% for event in msg %}
                 <!-- /. ROW  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- Advanced Tables -->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                 {{ event['event_name'] }}
                            </div>
                            <div class="panel-body">
                                <div>
                                    <table class="draw">
                                        <thead>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                            </tr>
                                             {% for player_set in event['players'] %}
                                            <tr>
                                                <td class="border_b"> {{ player_set[0]['index']}}&nbsp;</td>
                                                <td class="border_b drawrulercell drc_31" style="background-color: transparent;">
                                                    &nbsp;
                                                    <a href="">{{ player_set[0]['names'] }} </a>
                                                    <span id="3001" class="match">&nbsp;</span>
                                                </td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                            </tr>
                                                 <tr>
                                                <td>&nbsp;</td>
                                                <td class="border_r">&nbsp;&nbsp;</td>
                                                <td class="border_b drawrulercell drc_30" style="background-color: transparent;">
                                                    &nbsp;
                                                    <a href=""></a>
                                                    <span id="2001" class="match">&nbsp;</span>
                                                </td>
                                                <td>&nbsp;</td>
                                            </tr>

                                            <tr>
                                                <td class="border_b">{{ player_set[1]['index']}}&nbsp;</td>
                                                <td class="border_br drawrulercell drc_30" style="background-color: transparent;">
                                                    &nbsp;
                                                    <a href="">{{ player_set[1]['names'] }}</a>
                                                    <span id="3002" class="match">&nbsp;</span>
                                                </td>
                                                <!--<td class="border_r">
                                                    &nbsp;
                                                    <span class="score">
                                                        <span>21-16</span>
                                                        <span>21-18</span>
                                                    </span>
                                                    &nbsp;
                                                </td>
                                                <td>&nbsp;</td> -->
                                            </tr>

                                                 {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <!--End Advanced Tables -->
                    </div>
                </div>
                {% endfor %}
                
            </div>
        </div>

             <!-- /. PAGE INNER  -->
    </div>
         <!-- /. PAGE WRAPPER  -->
     <!-- /. WRAPPER  -->
    <!-- JS Scripts-->
    <!-- jQuery Js -->
<!--    <script src="assets/js/jquery-1.10.2.js"></script>-->
<!--      &lt;!&ndash; Bootstrap Js &ndash;&gt;-->
<!--    <script src="assets/js/bootstrap.min.js"></script>-->
<!--    &lt;!&ndash; Metis Menu Js &ndash;&gt;-->
<!--    <script src="assets/js/jquery.metisMenu.js"></script>-->
<!--     &lt;!&ndash; DATA TABLE SCRIPTS &ndash;&gt;-->
<!--    <script src="assets/js/dataTables/jquery.dataTables.js"></script>-->
<!--    <script src="assets/js/dataTables/dataTables.bootstrap.js"></script>-->
    <script>
            $(document).ready(function () {
                $('#dataTables-example').dataTable();
            });
    </script>
         <!-- Custom Js -->
<!--    <script src="assets/js/custom-scripts.js"></script>-->


</body>
</html>

templates/web/home.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>UA Badminton Tournament</title>
    <!-- Bootstrap Styles-->
    <link href="static/bootstrap.css" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link href="static/font-awesome.css" rel="stylesheet" />
    <!-- Morris Chart Styles-->
    <link href="assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />
    <!-- Custom Styles-->
    <link href="static/adminCustomStyle.css" rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

    <script>
        msg = "{{ msg }}";
        var data = JSON.parse(msg.replace(/&quot;/g, '"').replace(/&#39;/g, '"').replace(/[\u0000-\u001F]+/g, ""));

    </script>
</head>

<body>
    <div id="wrapper-public">
        <nav class="navbar navbar-default top-navbar-public" role="navigation">
            <div class="navbar-header-public">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url_for('web.home')}}">UA Badminton Tournament</a>
            </div>

            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="{{url_for('user.signin')}}" >Log In</a>
                </li>
            </ul>

        </nav>
        <!--/. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.home')}}"><i class="fa fa-dashboard"></i> HOME</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.tournament')}}"><i class="fa fa-edit"></i> Tournament</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.public_view_players')}}"><i class="fa fa-desktop"></i> Players</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.events')}}"><i class="fa fa-desktop"></i> Events</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.draws')}}"><i class="fa fa-desktop"></i> Draws</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.matches')}}"><i class="fa fa-table"></i> Matches</a>
                    </li>
                </ul>

            </div>

        </nav>

        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">


                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            UA Badminton Tournament Home <small></small>
                        </h1>
                    </div>
                </div>
                <!-- /. ROW  -->
                <div class="row">
                    <div class="col-md-6 col-sm-4">
                        <div class="panel panel-primary-public">
                            <div class="panel-heading">
                                Tournament Overview
                            </div>
                            <div class="panel-body">
                                <p id="tournament_name">{{ msg.tournament_name }}</p>
{#                                Date: 08/11/2023 <br>#}
                                Location: Tucson, USA <br>
                                Venue: {{ msg.location }} <br>
                                Contact: Julie Fan (juliefan@arizona.edu) <br>
                            </div>
                            <div class="panel-footer">
                                <a href="{{url_for('web.tournament')}}">More Details</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-sm-4">
                        <div class="panel panel-info-public">
                            <div class="panel-heading">
                                Tournament Announcement
                            </div>
                            <div class="panel-body">
                                {{ msg.announcements }}
                            </div>
                            <div class="panel-footer">
                                Last Updated: 04/22/2023
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /. ROW  -->
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
    <!-- JS Scripts-->
    <!-- jQuery Js -->
<!--    <script src="assets/js/jquery-1.10.2.js"></script>-->
<!--    &lt;!&ndash; Bootstrap Js &ndash;&gt;-->
<!--    <script src="assets/js/bootstrap.min.js"></script>-->
<!--    &lt;!&ndash; Metis Menu Js &ndash;&gt;-->
<!--    <script src="assets/js/jquery.metisMenu.js"></script>-->
<!--    &lt;!&ndash; Morris Chart Js &ndash;&gt;-->
<!--    <script src="assets/js/morris/raphael-2.1.0.min.js"></script>-->
<!--    <script src="assets/js/morris/morris.js"></script>-->
<!--    &lt;!&ndash; Custom Js &ndash;&gt;-->
<!--    <script src="assets/js/custom-scripts.js"></script>-->


</body>

</html>

templates/web/no_draws.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>UA Badminton Tournament</title>
	<!-- Bootstrap Styles-->
    <link href="static/bootstrap.css" rel="stylesheet" />
     <!-- FontAwesome Styles-->
    <link href="static/font-awesome.css" rel="stylesheet" />
     <!-- Morris Chart Styles-->

        <!-- Custom Styles-->
    <link href="static/adminCustomStyle.css" rel="stylesheet" />
    <link href="static/drawStyle.css" rel="stylesheet" />
     <!-- Google Fonts-->
   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
     <!-- TABLE STYLES-->
    <link href="static/dataTables.bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div id="wrapper-public">
        <nav class="navbar navbar-default top-navbar-public" role="navigation">
            <div class="navbar-header-public">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url_for('web.home')}}">UA Badminton Tournament</a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="{{url_for('user.signin')}}" >Log In</a>
                </li>
            </ul>
        </nav>
        <!--/. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.home')}}"><i class="fa fa-dashboard"></i> HOME</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.tournament')}}"><i class="fa fa-edit"></i> Tournament</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.public_view_players')}}"><i class="fa fa-desktop"></i> Players</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.events')}}"><i class="fa fa-desktop"></i> Events</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.draws')}}"><i class="fa fa-desktop"></i> Draws</a>
                    </li>
                    <li>
                        <a class="active-menu-public" href="{{url_for('web.matches')}}"><i class="fa fa-table"></i> Matches</a>
                    </li>
                </ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
			    <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            Draws <small></small>
                        </h1>
                    </div>
                </div>
                No draws set, Please check back later
            </div>
        </div>
    </div>
</body>
</html>